### PR TITLE
[ENHANCEMENT] Start pokemon story

### PR DESCRIPTION
**Pull request by JBYT27**

### CODE REVIEW

**Comment by TurnipGuy30** [comment]
Don't worry lol, I'll do the dialogue!

**Comment by JBYT27** [comment]
Haha, thanks! You could use the function `sp` that I made to create the dialogue and story btw.

**Comment by TurnipGuy30** [comment]
Yes, I see that; it's definitely better than just using `print()`! I didn't know you could make text like that in Python, so thank you!

**Comment by JBYT27** [comment]
Yep! No problem, glad I could help!

**Pull request merged**
