### PR TITLE
[DOCS] Update docs

### PR DESCRIPTION
**Pull request by JBYT27**

### CODE REVIEW

**Comment by JBYT27** [comment]
This includes code edits as well

**Comment by TurnipGuy30** [comment]
Can you please make sure that `main.py` links to `__init__.py`, or does that happen automatically?

**Comment by JBYT27** [comment]
It initializes the app, which doesn’t do anything as of right now, but should be handy and useful for longer codes

**Comment by TurnipGuy30** [comment]
Sounds good.

**Pull request merged**
