### PR TITLE
Parcel delivery

### PR DESCRIPTION
**Pull request by nasserkessas**
I have added the Pokemart in Viridian City and Oak's Parcel delivery hence I have also added Pokemart Functionality and obtaining the Pokedex. I have also updated the `items.json` file with all the items in the game.

### CODE REVIEW

**Comment by TurnipGuy30** [comment]
Haven't yet tested, but thanks for the help. A few things I should note:

- The `time.sleep()` commands during the intro sequence are timed to the Pokémon intro theme. I'm planning to add music at a later time. They can stay commented out for now, though.
- I know you're just going by the script, but in PPR, the rival doesn't speak, much like Red in canon. I can adjust the dialogue myself.

**Comment by nasserkessas** [comment]
Oh oops, I commented them out for my testing and forgot to add it back, sorry. It just took too long to wait each time I ran the game.

**Comment by nasserkessas** [comment]
Let me know if there's anything I should fix.

**Comment by TurnipGuy30** [comment]
Ooh, nice catch! I didn't notice that on my read-through.

**Comment by nasserkessas** [comment]
Haha neither did I, I was playing it and bought 5 Poke Balls and checked the save file and saw there was only one.

**Comment by TurnipGuy30** [comment]
I'm having a bug upon starting an encounter. I think it's with the weighted chances.

```
Current Location: Route 1 (North)

[w] - Go to Viridian City (South)
[s] - Go to Route 1 (South)

> s
Traceback (most recent call last):
  File "c:\[redacted]\Pokemon-PythonRed\app\main.py", line 1176, in <module>
    with get_encounter('route1-s', 'tall-grass')[0] as encounter:
  File "c:\[redacted]\Pokemon-PythonRed\app\main.py", line 643, in get_encounter
    return choices(pokemon, weights)[0]
  File "C:\Python310\lib\random.py", line 521, in choices
    cum_weights = list(_accumulate(weights))
TypeError: unsupported operand type(s) for +: 'dict' and 'float'

C:\[redacted]>
```

**Comment by nasserkessas** [comment]
Thats interesting, it works for me:
```
Current Location: Route 1 (North)

[w] - Go to Viridian City (South)
[s] - Go to Route 1 (South)

> s

A wild Pidgey appeared!

Go, Charmander!
```

**Comment by TurnipGuy30** [comment]
Are you on the latest commit of this branch?

**Comment by nasserkessas** [comment]
Yes, on this branch

**Comment by TurnipGuy30** [comment]
I'd think it would be the same, too.

**Pull request merged**
