### PR TITLE
[ENHANCEMENT] Clean up and fix code

### PR DESCRIPTION
**Pull request by JBYT27**
# Heya! 

I saw this Repo, and it looked pretty cool, but it needed a lot of fixes, so that's what I did!
What it includes are:

* Clean and short README
* A new JSON file for uploading databases and data to users
* A new LICENSE that fits the Repo
* Added Dependabot so your dependencies are up-to-date
* Cleaned up the python code, and added code to it
* And more!

I plan on adding more to this Pull Request, so maybe don't merge right away? If not, I can always leave more Pull Requests, so if you want, do feel free to merge (Your choice really :))

I hope this helps!

### CODE REVIEW

**Comment by JBYT27** [comment]
Also, if you want me to add back anything, let me know, I'll add it back on :D

**Comment by TurnipGuy30** [comment]
First off, just... wow. I actaully don't know what to say about the fact that someone went to this much effort to help me with this crazy task just dreamed up, then gave to myself. So I suppose what I should be saying now is a huge thanks. You've just encouraged me to keep going when I thought this project would be abandoned. When an official Pokemon game is made, they have a huge development team to handle graphics, story, mechanics, everything. So when one person wants to make an entire rewrite of a game, it should be viewed as crazy. But I knew I could do it, no matter how many useless lines, I wrote in the process. I knew that to do it well, I just needed a bit of help to get me started because compared to the experts, I can't use Python; I learned the basics just a year ago. But since you've gone to the effort, thank you. I told my friends that this is something I'd like to do, but none of my friends are programmers; I don't know of any programmers at my school. I had nobody to ask, so I just did it myself because I have the story planned out, and I wanted to prove to myself that I could do something like this, but really, I couldn't. So thanks for that push in the right direction.

Now that's out of the way, here's what I'm happy with:

- I'm happy to have someone go through the README; I find I have trouble keeping it short (like this comment!).
- I'm also glad to know what license to use, because seeing the list of options quickly overwhelmed me.

Also, some questions:

- How does Dependabot work? What does it actually do? Do I need to do anything to it?
- How do I use JSON with Python? I get the idea, but how exactly would the program retrieve information? If a module is used, can it write to JSON files too? Could I use that as a means of keeping saved progress?
- I noticed you removed the (attempt at) support for cross-platform use. Is there another way to do that, because if not, I'll just add it back in. I've already had someone ask about running on another OS, and that's not my field.
- How much more are you planning to do?

And a few other questions, not related to your changes:

- Can I please use the Contributors template you used in [io](https://github.com/TheIoLang/io#contributors-)? It looks so much better than what I've currently got.
- I don't really know what to say to people who have a Repo like [this](https://github.com/JBYT27/hello-world-in-many-langs), but then I check it and it's smaller than [mine](https://github.com/TurnipGuy30/Hello-World). See, I want to contribute, but at the same time, why have identical Repos? So if you want some help with that, let me know, because that's something I can do!
- Are you busy? I mean, would you be interested in joining the team? (Though, really, nobody else has actually done anything after the initial planning) I can see that you wouldn't really be able to write most of the code, because I'm the one with the story planned out (mentally), and anyway, why would you want to have another thing to do? You seem busy enough, looking at your recent contributions. Really, I just need to be shown how to use these new things, then I can do it myself. But if you'd be interested in helping more, it would be nice to have someone to work with.
- I just realised, you're part of [XPaVilion](https://github.com/XPaVilion) and [Grandmasters](https://github.com/Hax0rado). Do I know you from somewhere? Well, it seems Valensce does.

Again, thanks so much for this. I was really lost at what to do next, but this has shown me that there are people out there who can help. I'm sorry for making this so long, but I think that's my mind's way of saying thanks. Either that, or I just have trouble keeping things short.

Have a good one; you've earned it.

**Comment by JBYT27** [comment]
No problem! I'm glad that you got some motivation :)

* Basically, dependabot is a yml "bot" that checks your dependency files, such as `requirements.txt`, or `poetry.lock`, and then checks if the packages you installed need to be "bumped" to the latest version or not. Currently, there isn't a `poetry.lock` file or anything, but there probably will be, like a big project like this. Well, no, unless you're going to create more files that require other dependencies or if you're planning on using github actions on this project, which personally, I don't think is needed unless you're not confident with you're code and you think it has an error.
* Multiple ways really, but the most common way would be to append it to the json file using the json module, or just using the Python built-in function (which I'm pretty sure is `DICTIONARY_NAME["VALUE_NAME"] = VALUE`). The program would retrieve data with the json module, and the function `json.loads` or `json.load` to retrieve data, and `json.dumps` or `json.dump` to insert data into *json files*. Note that it's different than just inserting data into local Python dictionaries. Not 100%, but you could use other modules that keep databases such as `sqlite3`, or Replit's database, and keep the data in a json syntaxed way, so it's easy to collect the data, or just insert the whole json file into the database, and then save the data. However, you would need a hasher for this to prevent hackers into hacking the system.
* Well, pretty much all OS systems use the same command to clear the console, and it's most likely that it will always be the command `clear` to clear the console. However, if you feel like adding it back, I'll do that. But really, that part doesn't really matter.
* If I have enough time (which I probably do xD), a lot more, but I don't know the whole Pokemon story of Pokemon Red, so you may have to fill me in about that.

Okay, sure thing!
* Sure! If you take a look at `insights`, and then go to the `community` sub header, you can insert one I think. But feel free to use mine as a template :)
* Oh, to be honest, I just wanted to practice the languages I already knew and did it for fun lol. But yeah, thanks!!
* No, not really. Winter break is coming up at my school, so I should be free from the end of December to maybe mid-week of January. Your choice! I could just keep contributing through Pull Requests, so either is fine with me :) Nah, I like multi-tasking (even though half of time I fail at it lol).
* I used to be in Valensce's discord server, and we talked occasionally. Yeah, we just started talking because I put my discord tag on my profile.

No problem! I'm really happy that I could help 👍

You too! Happy holidays!

**Comment by TurnipGuy30** [comment]
Thanks for going through all the questions like that.

Sounds like a JSON module would be fairly easy to use, I'll look into it when the time comes.

About Pokemon Red: it wouldn't matter that you don't know the story, because I'm making a remix of it. It might be kinda hard to understand if you're not into the franchise, but basically, there are a lot of Pokemon games, and most of them take place in different places and/or times. Without giving spoilers: I plan to bring them all together.

Happy holidays to you too! Let me know once you've finished your (initial) changes.

**Comment by JBYT27** [comment]
No problem!

Well, not necessarily. It looks at the file, and then leaves a pull request if the dependents need to be updated. 

Oh, okay! Nah, I used to play pokemon a lot, but not much these days. Ooh, okay!

Ah, I see, makes sense :)

Sure thing! I’ll add more code to the main app, and then maybe you can add the story. Stay well!

**Comment by TurnipGuy30** [comment]
Sounds good. Thanks again!

**Comment by TurnipGuy30** [comment]
I'm going to merge the PR because I want to get the files in place so I can start working with the new environment as soon as possible. I don't think that would make a difference to whatever you're doing at the moment. I'm sure you understand!

**Comment by JBYT27** [comment]
Okay! Yep, sure thing! I’ll leave more PR’s for creating the app :)

**Pull request merged**
