### PR TITLE
Delete yml files + more

### PR DESCRIPTION
**Pull request by JBYT27**

### CODE REVIEW

**Comment by TurnipGuy30** [comment]
I'm not sure I understand; why were these changes necessary?

**Comment by JBYT27** [comment]
> I'm not sure I understand; why are these changes necessary? Is there something I'm doing wrong?

No, but it's just that;
1. The yml file/workflow you're using isn't necessary, and you're not really using it anyway in the README.
2. Some of the README descriptions are already given, and aren't necessary.
3. Just really deleting things that aren't needed.

You aren't doing anything wrong, but I'm just deleting everything that's not needed.

**Comment by TurnipGuy30** [comment]
The metrics are being used on the org profile, and I'm planning on using the other stuff for building since there isn't a GitHub Package for Python.

As for the Readme, I know it's cluttered but it's in case someone hasn't used Python before. For example, I have friends who aren't familiar with GitHub, but still want to play the game.

**Comment by JBYT27** [comment]
Oh, okay, I see! Do you want me to revert to the original branch?

**Comment by TurnipGuy30** [comment]
Yes please. I appreciate the effort you've gone to, though. Thank you.

**Comment by JBYT27** [comment]
Okay! No problem :)

**Pull request closed without merging**
