### PR TITLE
Moves

### PR DESCRIPTION
**Pull request by nasserkessas**
I have implemented basic Pokémon Move functionality into the game including:
- All level-up moves data from Generation 1 (source: [Pokeapi](https://pokeapi.co/))
- Move choices in the battle
- Move learning and forgetting by levelling up
- PP functionality
- Missing based on move accuracy
- Move type colouring
- Struggle move when Pokémon runs out of PP
- Updating the damage calculation

I have not added:
- Tm's and Hm's
- Effects of Abilities and Natures
- Pokémon Accuracy stat (accuracy is solely based on move's accuracy)
- Ability to check moves in the menu
- Ability to check move data before forgetting
- Trainer move selection, that is, trainers will select moves randomly without strategy. We will have to fix this in the future.

Note:
- Some game text I have written is not from the original Pokémon Red as I could not find screenshots for all circumstances 
- Move data is from the latest Generation, that is, if the move has changed (for example the base power) the game will use the newer values. This means MEWTWO for example will learn the move PSYSTRIKE at level 100 which wouldn't have happened in the original Pokémon Red.
- I have removed Pokémon not in Generation 1 as the method I used to retrieve the move data affected this. I also figured this is a waste of space unless you are planning on introducing trading or something.
- This also meant I removed the MISSINGNO. Pokémon. I'm not sure why this was there unless you wanted to reproduce the MISSINGNO. OLD MAN glitch 😆  

Feel free to ask me to fix anything with this PR (bugs, method etc.) or put any of the old data back as I'll be happy to do so.

Thanks

### CODE REVIEW

**Comment by TurnipGuy30** [comment]
I did have plans to host giveaways rewarding out-of-region Pokémon, but with you having set up the API connections, I'd rather re-work my plans to fit the new system. Thank you for this!

**Comment by nasserkessas** [comment]
No, its ok, I can easily add the Pokémon back, it's no problem

**Comment by TurnipGuy30** [comment]
Will the later-gen Pokémon fit the API standard that's already been implemented?

**Comment by nasserkessas** [comment]
The API has all the Pokémon and moves to date so I just have to update the array I used to iterate and generate the files. The later-gen Pokémon should work just fine with this system.

**Comment by TurnipGuy30** [comment]
I understand now. In that case, could you please add them back to the file?

**Comment by nasserkessas** [comment]
Yes sure, I'll add the moves for those Pokémon as well then. Would you like me to add MISSINGNO. back as well?

**Comment by TurnipGuy30** [comment]
Good question... If you can find some in-game stats for it, I'd be happy to include it.

**Comment by nasserkessas** [comment]
Ok, I'll have a look and push another commit soon.

**Comment by TurnipGuy30** [comment]
Much appreciated!

**Comment by nasserkessas** [comment]
Just a note: The original MISSINGNO. has the move WATER GUN [twice](https://bulbapedia.bulbagarden.net/wiki/MissingNo.#Learnset) but I'm not too sure if the game will accept this so I made it only have WATER GUN once.

**Comment by nasserkessas** [comment]
Another note: The last 7 Pokémon have no moves (Pokedex entries 899-905) and I thought I did something wrong but I checked the API and it actually returned an empty moves array. I'm not sure why this is but I think they might be updating the API at the moment.

**Comment by TurnipGuy30** [comment]
I've removed a few bugs in the database loading process, next I'll be testing the battle system.

**Comment by TurnipGuy30** [comment]
It seems to be working well. Thanks again for your contributions.

**Comment by nasserkessas** [comment]
Ah, good catch with those bugs, I hadn't noticed them when I tested it.

**Pull request merged**
