### PR TITLE
Linux Support Changes

### PR DESCRIPTION
**Pull request by TurnipGuy30**
Hi @JeremyLARDENOIS, if you have any changes that I haven't already taken on board, I'll add them with this PR! I'll just need to check over the files first. Thanks for your help!

### CODE REVIEW

**Comment by TurnipGuy30** [comment]
From now on, you don't have to work on a separate version, since one program can support both Windows and Linux.

**Comment by JeremyLARDENOIS** [comment]
Hello @TurnipGuy30, this was indeed a previous version that I made when #7 happened. It's true that I don't need to keep it. However, this version allows players to go further in the story. Do you want that I reimplement it and delete my fork? In plus, I kept this fork because I don't have the right to create a personal branch on your project :slightly_smiling_face: . If you don't want it, it's ok, we can keep this functioning of merge cross fork.
To finish, I wanted to say that the merge didn't do anything, but it's ok and normal (https://github.com/Pokemon-PythonRed/Pokemon-PythonRed/commit/0d0950d734984829fdead3c71279d0e780b6881b).

**Comment by TurnipGuy30** [comment]
Ah, I see, the merge didn't do anything... well that means the latest version is already compatible with Linux, just as planned!

Indeed, this fork goes further in the story, but I don't think it needs to be kept. The rewrite is changing a lot of the background processes, which I hope will make the code easier to organise, and I can easily remake those few rooms and the little bit of dialogue.

As much as I appreciate your effort to maintain a separate fork, I think it would be better for you to work directly on the original. I could invite you to collaborate in the @Pokemon-PythonRed organisation, which should make it much easier for us to work together. Let me know if that would help you, I'd be glad to do it!

Thanks again for all your help.

**Comment by JeremyLARDENOIS** [comment]
Yes it's true, the only thing that i did in my fork was to remove winsound, because it doesn't on linux.

Ok, no problem.

I will delete the fork so :slightly_smiling_face: . I will be happy to join the PPR organization:smile: .

If you need help with something, don't hesitate to ask, I will be happy to help.

**Comment by TurnipGuy30** [comment]
You've been invited! I believe the invite lasts for 7 days.

**Comment by JeremyLARDENOIS** [comment]
Accepted!

**Comment by TurnipGuy30** [comment]
Welcome on board! I've got to go now, but I'll see you around. Happy New Year if you're into that.

**Comment by JeremyLARDENOIS** [comment]
Thanks Captain! 

In 10 hours for me but thanks and happy new year to you :wink:

**Pull request merged**
